# Generated by Django 4.0.2 on 2022-02-01 20:18

import cafe.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=50)),
                ('lname', models.CharField(default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('telephone', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=15)),
                ('ingredients', models.TextField(default='', max_length=1000)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('ssn', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('fname', models.CharField(default='', max_length=50)),
                ('lname', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=100)),
                ('telephone', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cafe.person')),
                ('salary', models.FloatField(default=1500)),
            ],
            bases=('cafe.person',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(default=cafe.models.increment_booking_number, editable=False, max_length=20)),
                ('odate', models.DateField(blank=True, default=datetime.date(2022, 2, 1))),
                ('otime', models.TimeField(blank=True, default=datetime.time(23, 18, 24, 734586))),
                ('status', models.CharField(choices=[('queued', 'queued'), ('serving', 'serving'), ('ready', 'ready')], default='queued', max_length=10)),
                ('total_price', models.FloatField(default=0)),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cafe.customer')),
                ('worker', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.worker')),
            ],
        ),
    ]
