# Generated by Django 4.0.2 on 2022-02-05 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_menu_mitem_alter_order_odate_alter_order_otime'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='code',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Breakfast', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(blank=True, default=datetime.date(2022, 2, 5)),
        ),
        migrations.AlterField(
            model_name='order',
            name='otime',
            field=models.TimeField(blank=True, default=datetime.time(23, 38, 45, 963329)),
        ),
    ]
