# Generated by Django 4.0.2 on 2022-05-04 06:11

import cafe.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_alter_order_odate_alter_order_otime'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to=cafe.models.image_upload),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(blank=True, default=datetime.date(2022, 5, 4)),
        ),
        migrations.AlterField(
            model_name='order',
            name='otime',
            field=models.TimeField(blank=True, default=datetime.time(9, 11, 50, 685389)),
        ),
    ]
