# Generated by Django 4.0.2 on 2022-05-04 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_item_image_alter_menu_title_alter_order_odate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='otime',
            field=models.TimeField(blank=True, default=datetime.time(9, 21, 33, 110469)),
        ),
    ]
