# Generated by Django 4.0.2 on 2022-05-04 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_alter_order_otime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='otime',
            field=models.TimeField(blank=True, default=datetime.time(9, 49, 58, 941769)),
        ),
    ]
