# Generated by Django 4.0.2 on 2022-05-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0010_reserve_alter_order_odate_alter_order_otime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='otime',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='nperson',
            field=models.IntegerField(default=1),
        ),
    ]
