# Generated by Django 4.0.2 on 2022-05-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0013_order_iotem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('message', models.TimeField(default='', max_length=1000)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('nperson', models.IntegerField(default=1)),
            ],
        ),
    ]
