# Generated by Django 4.0.2 on 2022-05-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0014_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='message',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
