# Generated by Django 4.0.2 on 2022-05-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0015_alter_reserve_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
